<a href="https://colab.research.google.com/github/vipinkumarcp/NLP_Practice/blob/main/Wordtovec_and_bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd

In [55]:
messages =  pd.read_csv('/content/SMSSpamCollection',sep='\t',names=['lablel','message'])

In [56]:
messages

     lablel                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [57]:
messages.shape

(5572, 2)

In [58]:
messages['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [59]:
#data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [60]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [61]:
#stemming and stopwords
corpus = []
for i in range(0,len(messages)):
  # print(messages['message'][i])
  review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review = review.lower()
  review = review.split()
  # print(review)

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  # print(review)
  review = ' '.join(review)
  # print(review)
  corpus.append(review)

In [62]:
len(corpus)

5572

In [63]:
#creating the bag of the words

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True,ngram_range=(2,2))
#It creates a binary bag-of-words representation with a limited vocabulary of the most frequent 2500 terms.
X = cv.fit_transform(corpus).toarray()

In [64]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [65]:
y = pd.get_dummies(messages['lablel'])

In [66]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [67]:
y = y.iloc[:,1].values

In [68]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [70]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)
#

In [71]:
#prediction
y_pred = spam_detect_model.predict(X_test)

In [72]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9713004484304932
              precision    recall  f1-score   support

       False       0.97      1.00      0.98       955
        True       1.00      0.80      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115

In [73]:
#creating TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()
#

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [75]:
y_pred = spam_detect_model.predict(X_test)

In [76]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9847533632286996
              precision    recall  f1-score   support

       False       0.98      1.00      0.99       955
        True       1.00      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.98      0.98      1115